/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Open Library by title or author; each hit says if it is already in your library */
        get: operations["CatalogController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your books, most recently active first */
        get: operations["LibraryController_list"];
        put?: never;
        /** Add a book to your library */
        post: operations["LibraryController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One book with its recent reading events and the stacks it is in */
        get: operations["LibraryController_detail"];
        put?: never;
        post?: never;
        /** Remove a book from your library (its progress and stack memberships go with it) */
        delete: operations["LibraryController_remove"];
        options?: never;
        head?: never;
        /** Mark finished / put down (or undo either) */
        patch: operations["LibraryController_update"];
        trace?: never;
    };
    "/v1/library/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log progress by hand: exactly one of percent or page */
        post: operations["LibraryController_logProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your stacks with progress toward each goal, newest first */
        get: operations["StacksController_list"];
        put?: never;
        /** Create a stack (names are unique per user, case-insensitive) */
        post: operations["StacksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stacks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StacksController_detail"];
        put?: never;
        post?: never;
        /** Delete a stack; its books stay in your library */
        delete: operations["StacksController_remove"];
        options?: never;
        head?: never;
        /** Rename, re-describe, or change the target / due date (null clears) */
        patch: operations["StacksController_update"];
        trace?: never;
    };
    "/v1/stacks/{id}/books/{libraryBookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put a library book in the stack (idempotent) */
        put: operations["StacksController_addBook"];
        post?: never;
        /** Take a book out of the stack (idempotent; the book stays in your library) */
        delete: operations["StacksController_removeBook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/progress-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a reading event from a device (idempotent on externalId) */
        post: operations["ProgressController_ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CatalogBookDto: {
            /** @example OL5735363W */
            olWorkKey: string;
            title: string;
            authors: string[];
            /** @example https://covers.openlibrary.org/b/id/11200092-L.jpg */
            coverUrl: string | null;
            pageCount: number | null;
            firstPublishedYear: number | null;
            /** @description One primary genre mapped from Open Library subjects */
            genre: string | null;
            /**
             * Format: uuid
             * @description Set when this book is already in your library
             */
            libraryBookId: string | null;
        };
        ApiErrorDetail: {
            /** @example not_found */
            code: string;
            /** @example Library book not found */
            message: string;
            /**
             * @example {
             *       "name": "must be 1–80 characters"
             *     }
             */
            details?: {
                [key: string]: string;
            };
        };
        ApiErrorBody: {
            error: components["schemas"]["ApiErrorDetail"];
        };
        BookDto: {
            /** @example OL5735363W */
            olWorkKey: string;
            title: string;
            authors: string[];
            /** @example https://covers.openlibrary.org/b/id/11200092-L.jpg */
            coverUrl: string | null;
            pageCount: number | null;
            firstPublishedYear: number | null;
            /** @description One primary genre mapped from Open Library subjects */
            genre: string | null;
        };
        ProgressDto: {
            /** @description Canonical unit (e-readers report percent). 0 when nothing logged. */
            percent: number;
            page: number | null;
            /** @enum {string|null} */
            source: "manual" | "device" | "kindle_sim" | null;
            /** Format: date-time */
            occurredAt: string | null;
        };
        PaceDto: {
            /** @description Percent gained over the trailing 14 days ÷ 14; null unless reading */
            percentPerDay: number | null;
            pagesPerDay: number | null;
            /**
             * Format: date-time
             * @description Projected finish; null when pace ≤ 0
             */
            eta: string | null;
        };
        LibraryBookDto: {
            /** Format: uuid */
            id: string;
            book: components["schemas"]["BookDto"];
            /** @enum {string} */
            status: "want_to_read" | "reading" | "finished" | "abandoned";
            /** Format: date-time */
            addedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
            progress: components["schemas"]["ProgressDto"];
            pace: components["schemas"]["PaceDto"];
        };
        AddToLibraryBody: {
            /**
             * @description Open Library work key (from /v1/catalog/search)
             * @example OL5735363W
             */
            olWorkKey: string;
        };
        ReadingEventDto: {
            id: string;
            percent: number;
            page: number | null;
            /** @enum {string} */
            source: "manual" | "device" | "kindle_sim";
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            receivedAt: string;
        };
        StackRefDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        LibraryBookDetailDto: {
            /** Format: uuid */
            id: string;
            book: components["schemas"]["BookDto"];
            /** @enum {string} */
            status: "want_to_read" | "reading" | "finished" | "abandoned";
            /** Format: date-time */
            addedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
            progress: components["schemas"]["ProgressDto"];
            pace: components["schemas"]["PaceDto"];
            /** @description Newest first (by when you read, not when it arrived), max 50 */
            events: components["schemas"]["ReadingEventDto"][];
            stacks: components["schemas"]["StackRefDto"][];
        };
        UpdateLibraryBookBody: {
            /** @description true marks it finished now; false clears an explicit finish */
            finished?: boolean;
            /** @description true puts it down; false picks it back up */
            abandoned?: boolean;
        };
        LogProgressBody: {
            /** @example 42.5 */
            percent?: number;
            /** @example 210 */
            page?: number;
        };
        StackPreviewBookDto: {
            /** Format: uuid */
            libraryBookId: string;
            title: string;
            coverUrl: string | null;
            pageCount: number | null;
            /** @enum {string} */
            status: "want_to_read" | "reading" | "finished" | "abandoned";
        };
        StackSummaryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            targetCount: number | null;
            /** Format: date */
            dueOn: string | null;
            /** Format: date-time */
            createdAt: string;
            bookCount: number;
            finishedCount: number;
            /** @description targetCount, or bookCount when there is no target */
            goal: number;
            /** @description null without a due date; otherwise finished/goal ≥ fraction of [created, due] elapsed */
            onTrack: boolean | null;
            /** @description First 8 books in stack order */
            preview: components["schemas"]["StackPreviewBookDto"][];
        };
        CreateStackBody: {
            /** @example Autumn sci-fi */
            name: string;
            description?: string | null;
            /** @description How many books to finish */
            targetCount?: number | null;
            /**
             * Format: date
             * @example 2026-12-31
             */
            dueOn?: string | null;
        };
        StackDetailDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            targetCount: number | null;
            /** Format: date */
            dueOn: string | null;
            /** Format: date-time */
            createdAt: string;
            bookCount: number;
            finishedCount: number;
            /** @description targetCount, or bookCount when there is no target */
            goal: number;
            /** @description null without a due date; otherwise finished/goal ≥ fraction of [created, due] elapsed */
            onTrack: boolean | null;
            /** @description First 8 books in stack order */
            preview: components["schemas"]["StackPreviewBookDto"][];
            /** @description All books, in stack order */
            books: components["schemas"]["LibraryBookDto"][];
        };
        UpdateStackBody: {
            name?: string;
            description?: string | null;
            targetCount?: number | null;
            /** Format: date */
            dueOn?: string | null;
        };
        DeviceProgressEventBody: {
            /** Format: uuid */
            libraryBookId: string;
            percent: number;
            /**
             * Format: date-time
             * @description When the reading happened (not when it was sent)
             */
            occurredAt: string;
            /** @description The device's own id for this event; resending it is a no-op */
            externalId: string;
        };
        DeviceProgressAccepted: {
            /** @description false when this externalId was already recorded */
            recorded: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_search: {
        parameters: {
            query: {
                /** @description Title and/or author */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogBookDto"][];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Open Library is down or slow */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    LibraryController_list: {
        parameters: {
            query?: {
                /** @description Only books with this derived status */
                status?: "want_to_read" | "reading" | "finished" | "abandoned";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBookDto"][];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    LibraryController_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToLibraryBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBookDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Conflicts with existing data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    LibraryController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBookDetailDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    LibraryController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    LibraryController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLibraryBookBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBookDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    LibraryController_logProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogProgressBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBookDetailDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    StacksController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackSummaryDto"][];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    StacksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStackBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackSummaryDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Conflicts with existing data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    StacksController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackDetailDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    StacksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    StacksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStackBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackSummaryDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Conflicts with existing data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    StacksController_addBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                libraryBookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackDetailDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    StacksController_removeBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                libraryBookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackDetailDto"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    ProgressController_ingest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceProgressEventBody"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceProgressAccepted"];
                };
            };
            /** @description Validation failed (details has one message per field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Missing, unknown or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Valid key, wrong scope (a device key on a user endpoint) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Not found, or it belongs to someone else (we don't say which) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
}
